# Generated by Django 4.0.2 on 2022-03-01 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('message', models.CharField(max_length=100)),
                ('dateTime', models.CharField(max_length=26)),
                ('idOperacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.operacao')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultaAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=10)),
                ('idOperacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.operacao')),
            ],
        ),
    ]
