# Generated by Django 4.0.2 on 2022-03-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_logapi_idoperacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultaapi',
            old_name='date',
            new_name='data2',
        ),
        migrations.AddField(
            model_name='consultaapi',
            name='date1',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
