# Generated by Django 4.0.2 on 2022-03-05 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_data2_consultaapi_date2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultaapi',
            old_name='date1',
            new_name='dataFinal',
        ),
        migrations.RenameField(
            model_name='consultaapi',
            old_name='date2',
            new_name='dataInicio',
        ),
    ]
