# Generated by Django 4.0.2 on 2022-03-09 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_covidcases_alter_consultaapi_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidcases',
            name='num_sequences',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='covidcases',
            name='num_sequences_total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='covidcases',
            name='perc_sequences',
            field=models.IntegerField(),
        ),
    ]
