# Generated by Django 4.0.2 on 2022-03-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_delete_covidcases'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidCases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('variant', models.CharField(max_length=10)),
                ('num_sequences', models.IntegerField()),
                ('perc_sequences', models.IntegerField()),
                ('num_sequences_total', models.IntegerField()),
            ],
        ),
    ]
