# Generated by Django 4.0.2 on 2022-03-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_covidcases_perc_sequences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidcases',
            name='variant',
            field=models.CharField(max_length=20),
        ),
    ]
