# Generated by Django 4.0.2 on 2022-03-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_covidcases_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='logapi',
            name='operation',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
