# Generated by Django 4.0.2 on 2022-04-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='returnConsultaCases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
