# Generated by Django 4.0.2 on 2022-04-26 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100)),
                ('idOperacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.operacao')),
            ],
        ),
    ]
